"""LangGraph workflow state schema."""

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


class WorkflowState(BaseModel):
    """LangGraph workflow state.

    This state is passed between nodes and persisted to Redis.
    """

    # Core identifiers
    ticket_id: str = Field(..., description="Jira ticket ID (e.g., PROJ-46)")
    thread_id: str = Field(..., description="Workflow thread ID (typically same as ticket_id)")

    # Workflow metadata
    current_node: Optional[str] = Field(None, description="Currently executing node")
    last_node: Optional[str] = Field(None, description="Last completed node")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Jira sync (orchestration layer uses these)
    next_status: Optional[str] = Field(None, description="Next Jira status to transition to")
    current_status: Optional[str] = Field(None, description="Current Jira status (from webhook input)")

    # Feedback mode
    feedback_mode: bool = Field(default=False, description="True if regenerating with feedback")
    feedback_comment: Optional[str] = Field(None, description="Latest human feedback")

    # Artifacts (generated by nodes)
    prd: Optional[str] = Field(None, description="Generated PRD (markdown)")
    epic_data: list[dict[str, Any]] = Field(default_factory=list, description="Epic definitions before Jira creation")
    epic_keys: list[str] = Field(default_factory=list, description="Created Epic keys")
    story_data: list[dict[str, Any]] = Field(default_factory=list, description="Story definitions before Jira creation")
    story_keys: list[str] = Field(default_factory=list, description="Created Story keys")
    spec: Optional[str] = Field(None, description="Generated spec (markdown)")
    plan: Optional[str] = Field(None, description="Generated plan (markdown)")

    # Context (from node_5)
    repositories: dict[str, Any] = Field(
        default_factory=dict, description="Affected repositories and their context"
    )
    constitutions: dict[str, Any] = Field(
        default_factory=dict, description="Constitution.md rules per repo"
    )

    # Research (from discovery)
    system_catalog_results: dict[str, Any] = Field(
        default_factory=dict, description="System catalog search results"
    )
    related_tickets: list[str] = Field(
        default_factory=list, description="Related Jira ticket keys"
    )

    # Error tracking
    error_count: int = Field(default=0, description="Number of errors encountered")
    last_error: Optional[str] = Field(None, description="Last error message")

    # Custom data (extensible)
    custom_data: dict[str, Any] = Field(
        default_factory=dict, description="Additional custom data"
    )

    class Config:
        """Pydantic config."""

        json_schema_extra = {
            "example": {
                "ticket_id": "PROJ-46",
                "thread_id": "ticket_PROJ-46",
                "current_node": "node_1_ideation_agent",
                "feedback_mode": False,
                "prd": "# PRD: Password Reset Feature\n...",
                "epic_keys": ["PROJ-14", "PROJ-15"],
            }
        }
